SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Mining Rush Test"

SPRITE_SCALING = 0.3
SPRITE_PIXEL_SIZE = 128
SCALED_PIXEL_SIZE = (SPRITE_PIXEL_SIZE * SPRITE_SCALING)

VIEWPORT_MARGIN = 256
RIGHT_MARGIN = 256
